defaults:
  theme: dark
  max_columns: 100
  max_columns_alignment: left

transition:
    duration_millis: 100
    frames: 90
    animation:
      style: slide_horizontal

mermaid:
  scale: 20

options:
  implicit_slide_ends: true
  incremental_lists: true 
